##########################################################################
#
#                                 项目配置
#
##########################################################################
server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: dev

##########################################################################
#                                 日志配置
##########################################################################
logging:
  level.root: info
  level.org.tan: debug
  path: d:\\logs\\
  file: seckill.log

---

spring:
  profiles: dev
##########################################################################
#
# 开发环境配置
#
##########################################################################
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-request-size: 100MB
      #文件上传大小限制
      max-file-size: 100MB
  http:
    encoding:
      enabled: true
      force: true


##########################################################################
#
#                               数据源配置
#
##########################################################################
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Hongkong
    druid:
        # 这一项可配可不配，如果不配置druid会根据url自动识别dbType，然后选择相应的driverClassName
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/weixin?useUnicode=true&characterEncoding=utf8&useSSL=false
#        username: root
#        password: 123456
#         初始化物理连接个数，默认值0
        initial-size: 5
        # 最大连接数，默认值8
        max-active: 8
        # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
        max-wait: 60000
        # 最小连接数，默认值8
        min-idle: 8
        # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-borrow: true
        # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-return: true
        # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        test-while-idle: true
        # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
        validation-query: SELECT 'x'


##########################################################################
#
# Redis缓存配置
#
##########################################################################
  redis:
      database: 1
      password: ''
      # 连接超时时间
      timeout: 5000
      jedis:
        pool:
          max-active: 1000
          max-wait: -1
          max-idle: 10
          min-idle: 2


##########################################################################
#
# thymeleaf静态资源配置
#
##########################################################################
  thymeleaf:
      cache: false
      encoding: UTF-8
      mode: HTML
      prefix: classpath:/templates/thymeleaf/
      suffix: .html
#      template-resolver-order: 0


##########################################################################
#
# mybatis配置
#
##########################################################################
mybatis:
  type-aliases-package: org.tan.seckill.po
  mapper-locations: /mapper/**.xml
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true


##########################################################################
#
# mapper配置
#
##########################################################################
mapper:
  mappers:
    - org.tan.seckill.core.utils.MyMapper
  not-empty: false
  identity: MYSQL


##########################################################################
#
# pagehelper配置
#
##########################################################################
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql